# set server port
server:
  port: 9000  # 配置端口
  servlet:
    context-path: /
  address: localhost

# spring mvc
spring:
#  mvc:
    #static-path-pattern: /static/**
#    view: # 默认前后缀
#          prefix: /
#          suffix: .html

  datasource: # set database config
    url: jdbc:mysql://localhost:3306/vuedemo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# 日志配置
logging:
  config: classpath:logback-boot.xml
